remote_write:
  - url: http://localhost:8428/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      max_shards: 30
scrape_configs:
  - job_name: redis_exporter
    static_configs:
    - targets: ['localhost:9121']      
